[package]
name = "digit_bin_index"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A high-performance data structure for weighted random sampling of binned probabilities."
repository = "https://github.com/Roenbaeck/digit-bin-index" 

[dependencies]
fraction = "0.15"
rand = "0.9"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "selection_benchmark"
harness = false

